#!/bin/bash
#naam bin specify
mkdir $1/Afbeeldingen #Map aanmaken met 1e argument

find $1 -name '*.jpg' -exec mv {} $1/Afbeeldingen \; #Zoek .png en .jpg files en moved ze naar de aangemaakte directory
find $1 -name '*.png' -exec mv {} $1/Afbeeldingen \; #Zoek .png en .jpg files en moved ze naar de aangemaakte directory


#line in terminal ./sorteerAfbeeldingen /home/user/PATH/TO/Files
